server:
  port: 88
spring:
  application:
    name: cloud-consumer-feign-hystrix-order87
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: false
    #是否从EurekaServer抓取已有的注册消息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
       #单机版
      #defaultZone: http://localhost:7001/eureka
feign:
  hystrix:
    enabled: true
#ribbon:
#  # 设置简历连接所用的时间，适用于网络正常情况下，两端连接所用的时间
#  ReadTimeout: 5000
#  # 设置 建立连接后，从服务端读取到可用资源的所用时间
#  ConnectTimeout: 5000